spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
s3:
  endpointUrl: http://127.0.0.1:9000
  accessKey: 2QURXNTC110AQG7G7R6P
  secretKey: eK/uMkgLpUPV7lhDvQ7cnJRRno1xMFiSzxY4Vm+r
  bucketName: moviefun